### ISSUE TITLE
Missing example showing ClerkAuth with a server component that fetches data

### ISSUE THREAD

**Issue by mbrameld** [HamedBahram/next-ecomm#1]
The Products page is a server component that fetches data with the new paradigm, but the repo doesn't show how to use Clerk in the same component. What if the data being fetched is dependent on the user ID, can it then only be fetched from client components?

**Comment by HamedBahram** [comment]
> The Products page is a server component that fetches data with the new paradigm, but the repo doesn't show how to use Clerk in the same component. What if the data being fetched is dependent on the user ID, can it then only be fetched from client components?

The clerk repo has had an update since I last created this example. I'll have to make an updated video and project reflecting the changes, so stay tuned. But to answer your question, you can also check the session and protect your server-rendered pages without turning them into client components. You can use the `auth` function to get the `userId` for example: 

```
import { auth } from '@clerk/nextjs';

export default function Home() {
  const { userId } = auth();
  return <div>User Id: {userId}</div>;
}
```
